# Generated by Django 3.2.16 on 2022-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('sub_title', models.TextField(max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
